name: cmi-qa

services:
  app:
    image: cmi:latest
    command: php think swoole
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    build: 
      context: ../../
      dockerfile: ./docker/qa/Dockerfile
    expose:
      - 8324
    volumes:
      - ../../public/uploads:/var/www/public/uploads

  # 先暂时把 crawler 放在 web 文件夹下面, 后面有需要再改
  crawler:
    build: 
      context: ../../../crawler
    restart: always
    expose:
      - 5000
    env_file:
      - crawler.env
  
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

  mysql:
    image: mysql:5.7
    command: --sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./data/mysql:/var/lib/mysql
    # ports:
    #   - 3306:3306
    env_file:
      - mysql.env
    healthcheck:
      test: mysqladmin ping -h localhost --password=$$MYSQL_ROOT_PASSWORD
      start_period: 0s
      start_interval: 1s
      interval: 1s
      timeout: 1s
      retries: 3 

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/var/lib/redis/data
    # ports:
    #   - 6379:6379